"""Content pipeline: scrape pedsconcussion.com, compare against Supabase, update what changed.

Three scrapes, three comparisons, three sinks:

    recommendations   -> content_state       -> the six copilots' instructions
    tool links        -> vector_store_files  -> the Fuel IX vector store
    EN + FR listings  -> resource_pairs      -> the map the app resolves French links from

Supabase holds the "what we have" side of each comparison, so a sink only fires when its own
scrape actually differs. `api/cron.py` runs all three nightly on Vercel; `cli refresh` runs the
same work locally.

Contrary to what an earlier version of this docstring said, this is NOT a build-time pipeline.
It runs against live infrastructure, at request time for the pairing table and on a schedule for
the rest. The one genuinely build-time artefact left is `lib/i18n/resourceLinks.data.ts`, an
offline fallback regenerated by `cli render`.
"""
