"""Serve the EN->FR resource link map at runtime, and the admin view that curates it.

`lib/i18n/resourceLinks.data.ts` is bundled at build time, so on its own the French links
could only change when someone redeployed. This endpoint makes them self-updating with no
storage and nothing to maintain: Vercel's CDN is the cache.

**Everything here derives from the live scrape. No URL in this system is hand-written.**

  auto    tool-number matches computed from the live listings — outil 6.1 == tool 6.1, exact
          and deterministic, the only thing allowed to publish itself unreviewed
  manual  pairs a human made in /admin/scraping, held in the Supabase override store

`data/resource-pairs.json` is the *snapshot* of the last good scrape, regenerated by
`cli refresh` — an offline fallback, not a source of truth. It used to carry hand-curated
pairs as well, and three of them pointed at resources outside the Living Guideline Tools
section (SCAT6, Child SCAT6, SCOAT6). That forced the admin report to synthesise placeholder
"alias" rows so those pairs were not left dangling, which is why the English column read 30
against a 27-tool scrape. Both the curated pairs and the placeholders are gone.

There used to be a third, weaker matching tier — shared identifiers, e.g. two pages both
mentioning SCAT6 — which produced proposals for a human but never published. It is gone.
Pointing a clinician at a near-neighbour document is exactly the failure this design exists to
prevent, and an unpaired resource falls back to the English original, which is always a safe
answer.

If this endpoint fails the frontend keeps using the bundled map, so the worst case is stale
links rather than missing ones.
"""

from __future__ import annotations

import os
import sys
import time
from typing import Any, Dict, List, Optional

from fastapi import FastAPI, Header, HTTPException
from fastapi.responses import JSONResponse
from pydantic import BaseModel

sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

app = FastAPI()

# Recomputed at most once every 15 minutes, with a stale window that keeps serving the last good
# map for a week if a recompute ever fails, so an upstream outage cannot blank the links.
#
# This used to be a day. It came down because manual pairings are now live data: a reviewer who
# pairs two documents should see it take effect in minutes, not tomorrow. `stale-while-
# revalidate` means the shorter window costs background revalidations, not user-visible latency.
CACHE_CONTROL = "public, s-maxage=900, stale-while-revalidate=604800"


def _effective_pair_set():
    """The reviewed baseline with the manual overrides layered on top.

    Returns ``(pair_set, override_set)``. Reading the overrides never raises; if the store is
    unreachable this is exactly the committed baseline, which is the correct thing to fall back
    to — stale links rather than none.
    """
    from scripts.content_pipeline.overrides import layer, load as load_overrides
    from scripts.content_pipeline.pairs import PairSet

    base = PairSet.load()
    override_set = load_overrides()
    return layer(base, override_set), override_set


def _build_map() -> Dict[str, Any]:
    from scripts.content_pipeline.fetch import fetch_all, living_tools
    from scripts.content_pipeline.match import TIER_TOOL_NUMBER, match_resources
    from scripts.content_pipeline.urls import normalize_url

    pair_set, override_set = _effective_pair_set()

    pairs: Dict[str, Dict[str, str]] = {}
    for pair in pair_set.pairs:
        entry: Dict[str, str] = {"url": pair.fr_url}
        if pair.fr_title:
            entry["title"] = pair.fr_title
        pairs[pair.en_url] = entry

    # Seeded from the snapshot, then overwritten by the live listing below. The snapshot is
    # itself the last good scrape, so this is the offline fallback rather than a second source
    # of truth: if the fetch fails, the previous run's French set is still the right answer.
    french_urls = {normalize_url(url) for url in pair_set.french_urls}
    french_urls |= {normalize_url(pair.fr_url) for pair in pair_set.pairs}

    added = 0
    errors: list[str] = []
    if override_set.error:
        errors.append(f"override store: {override_set.error}")

    # `layer` has already dropped suppressed pairs, which takes them out of the matcher's index
    # and therefore makes them candidates again. Without this the matcher would hand straight
    # back the link a reviewer just removed.
    suppressed = override_set.suppressed()

    try:
        fetched = fetch_all()
        errors.extend(fetched.errors)
        # Everything the live listing calls French is French, whether or not anything pairs to
        # it. This is what stops `localizeLink` marking a French document "(en anglais)".
        french_urls |= {normalize_url(r.url) for r in fetched.french_resources}
        result = match_resources(
            living_tools(fetched.english_tools), fetched.french_resources, pair_set
        )
        for proposal in result.auto:
            # This is the path that reaches production without review, so the tier is re-checked
            # rather than assumed: only an exact tool-number match may publish itself.
            if proposal.tier != TIER_TOOL_NUMBER or proposal.en.url in pairs:
                continue
            if normalize_url(proposal.en.url) in suppressed:
                continue
            entry = {"url": proposal.fr.url}
            if proposal.fr.title:
                entry["title"] = proposal.fr.title
            pairs[proposal.en.url] = entry
            french_urls.add(normalize_url(proposal.fr.url))
            added += 1
    except Exception as exc:
        # A scrape failure must not empty the map — fall back to curated pairs only.
        errors.append(f"{type(exc).__name__}: {exc}")

    return {
        "pairs": pairs,
        "frenchUrls": sorted(french_urls),
        "meta": {
            "curated": len(pair_set.pairs),
            "autoAdded": added,
            "total": len(pairs),
            "errors": errors,
        },
    }


@app.get("/api/resource-links")
def resource_links() -> JSONResponse:
    started = time.perf_counter()
    payload = _build_map()
    payload["meta"]["elapsed_ms"] = int((time.perf_counter() - started) * 1000)
    return JSONResponse(payload, headers={"Cache-Control": CACHE_CONTROL})


# --- admin report -------------------------------------------------------------------------
#
# The map above is what the app consumes. This is the human view of the same data, shaped for a
# two-column workbench: every English Living Guideline Tool, every French resource, and the
# links and refusals between them as separate lists — so the UI can render either side
# independently rather than being forced into an English-per-row table.
#
# Both sides run through the same `living_tools` narrowing as the map — and as the refresh job
# that writes the snapshot — so what a reviewer can see here is exactly what is allowed to
# publish. A resource that could pair itself without ever appearing in this view would be a link
# nobody could audit or undo.

# A pairing has exactly two possible provenances: the matcher found it, or a person made it.
ORIGIN_MANUAL = "manual"
ORIGIN_AUTO = "auto"

# How a snapshot pair's recorded `source` maps onto the origins the UI shows. Anything not
# listed falls through to manual, which is the honest default: a pair the matcher did not
# produce got there because someone put it there.
_ORIGIN_BY_SOURCE = {
    "manual": ORIGIN_MANUAL,
    "tool-number": ORIGIN_AUTO,
}


def _is_pdf(url: str) -> bool:
    return (url or "").split("?")[0].rstrip("/").lower().endswith(".pdf")


def _host(url: str) -> str:
    from urllib.parse import urlsplit

    return (urlsplit(url or "").netloc or "").lower().removeprefix("www.")


def _resource_entry(resource: Any) -> Dict[str, Any]:
    return {
        "title": resource.title,
        "url": resource.url,
        "toolNumber": resource.tool_number,
        "group": getattr(resource, "group", "") or "",
        "sourcePage": getattr(resource, "source_page", "") or "",
        "host": _host(resource.url),
        "isPdf": _is_pdf(resource.url),
        "offListing": False,
    }


def _placeholder_entry(url: str, title: str = "") -> Dict[str, Any]:
    """A resource referenced by a pair but absent from the live listing.

    Should never be reached now that pairs can only come from the listings themselves. Kept as
    a dangling-reference guard: if the site moves a URL out from under a recorded pairing, the
    row still renders — flagged — instead of vanishing from the one view that could fix it.
    """
    return {
        "title": title,
        "url": url,
        "toolNumber": None,
        "group": "",
        "sourcePage": "",
        "host": _host(url),
        "isPdf": _is_pdf(url),
        "offListing": True,
    }


def _build_report() -> Dict[str, Any]:
    from scripts.content_pipeline.fetch import fetch_all, living_tools
    from scripts.content_pipeline.match import TIER_TOOL_NUMBER, match_resources
    from scripts.content_pipeline.overrides import KIND_PAIR
    from scripts.content_pipeline.pairs import PairSet
    from scripts.content_pipeline.urls import normalize_url

    pair_set, override_set = _effective_pair_set()
    fetched = fetch_all()
    english_tools = living_tools(fetched.english_tools)
    errors = list(fetched.errors)

    # Override id by English URL, so each row in the UI can carry its own delete button.
    manual_pair_ids = {
        normalize_url(item.en_url): item
        for item in override_set.of_kind(KIND_PAIR)
    }

    result = match_resources(english_tools, fetched.french_resources, pair_set)

    # Second pass against an EMPTY pair set, to learn what the matcher would propose for
    # resources that already have a recorded pairing — something the live pass cannot say,
    # because it skips anything already paired.
    #
    # This exists for one signal: a *conflict*, where the matcher independently points a
    # resource at a different French page than the one recorded. That disagreement is worth
    # surfacing; it usually means the listing changed under a hand-made pair.
    cold_result = match_resources(english_tools, fetched.french_resources, PairSet())
    derivable = {
        normalize_url(p.en.url): normalize_url(p.fr.url) for p in cold_result.auto
    }

    # --- links ------------------------------------------------------------------------
    links: List[Dict[str, Any]] = []

    for pair in pair_set.pairs:
        en_key = normalize_url(pair.en_url)
        override = manual_pair_ids.get(en_key)
        origin = _ORIGIN_BY_SOURCE.get(pair.source, ORIGIN_MANUAL)

        link: Dict[str, Any] = {
            "enUrl": pair.en_url,
            "frUrl": pair.fr_url,
            "frTitle": pair.fr_title or "",
            "origin": origin,
            "note": pair.note or "",
            "overrideId": override.id if override else None,
            "createdAt": override.created_at if override else None,
        }

        # Would the matcher find this pair unaided, and would it agree?
        target = derivable.get(en_key)
        if target:
            link["derivable"] = (
                ORIGIN_AUTO if target == normalize_url(pair.fr_url) else "conflict"
            )
        links.append(link)

    # Live proposals for resources that have no recorded pair. These are not yet decisions —
    # the UI shows them as suggestions the reviewer can confirm or reject.
    recorded_en = {normalize_url(link["enUrl"]) for link in links}
    suppressed = override_set.suppressed()
    for proposal in result.auto:
        if normalize_url(proposal.en.url) in recorded_en:
            continue
        # Removed by a reviewer. Re-suggesting it is how a removal quietly undoes itself.
        if normalize_url(proposal.en.url) in suppressed:
            continue
        links.append(
            {
                "enUrl": proposal.en.url,
                "frUrl": proposal.fr.url,
                "frTitle": proposal.fr.title or "",
                "origin": ORIGIN_AUTO,
                "note": proposal.evidence,
                "overrideId": None,
                "createdAt": None,
                "proposed": True,
            }
        )

    # --- columns ----------------------------------------------------------------------
    english: Dict[str, Dict[str, Any]] = {}
    for resource in english_tools:
        english.setdefault(normalize_url(resource.url), _resource_entry(resource))

    french: Dict[str, Dict[str, Any]] = {}
    for resource in fetched.french_resources:
        french.setdefault(normalize_url(resource.url), _resource_entry(resource))

    # Anything a link references must exist in its column, or the UI would hold a dangling
    # reference and silently drop the row. With both sides scrape-derived this should never
    # fire — a pair can only reference what the listings carry — so a placeholder appearing
    # here means the site moved a URL out from under a recorded pairing, which is worth seeing
    # rather than hiding.
    for link in links:
        english.setdefault(normalize_url(link["enUrl"]), _placeholder_entry(link["enUrl"]))
        french.setdefault(
            normalize_url(link["frUrl"]), _placeholder_entry(link["frUrl"], link["frTitle"])
        )

    english_list = sorted(english.values(), key=lambda item: (item["offListing"], _sort_key(item)))
    french_list = sorted(french.values(), key=lambda item: (item["offListing"], _sort_key(item)))

    # --- summary ----------------------------------------------------------------------
    settled = [link for link in links if not link.get("proposed")]
    linked_en = {normalize_url(link["enUrl"]) for link in links}
    linked_fr = {normalize_url(link["frUrl"]) for link in links}

    summary = {
        "english": len(english_list),
        "french": len(french_list),
        "paired": len(settled),
        "proposed": len(links) - len(settled),
        "manual": sum(1 for link in links if link["origin"] == ORIGIN_MANUAL),
        "auto": sum(1 for link in links if link["origin"] == ORIGIN_AUTO),
        "unpairedEnglish": sum(
            1 for item in english_list if normalize_url(item["url"]) not in linked_en
        ),
        "unpairedFrench": sum(
            1 for item in french_list if normalize_url(item["url"]) not in linked_fr
        ),
        "manualOverrides": len(override_set.overrides),
    }

    return {
        "english": english_list,
        "french": french_list,
        "links": links,
        "summary": summary,
        "store": {
            "configured": override_set.configured,
            "available": override_set.available,
            "error": override_set.error,
            "overrides": len(override_set.overrides),
        },
        "authRequired": _auth_required(),
        "errors": errors,
    }


def _sort_key(item: Dict[str, Any]) -> tuple:
    """Tool number first and numerically, then title. Keeps 2.1 above 10.1."""
    number = item.get("toolNumber")
    if number:
        try:
            major, minor = (int(part) for part in str(number).split("."))
            return (0, major, minor, "")
        except ValueError:
            pass
    return (1, 0, 0, (item.get("title") or item.get("url") or "").lower())


@app.get("/api/resource-links/report")
def resource_links_report() -> JSONResponse:
    started = time.perf_counter()
    payload = _build_report()
    payload["elapsedMs"] = int((time.perf_counter() - started) * 1000)
    # No caching: this view is now editable, and a reviewer must see their own change land.
    return JSONResponse(payload, headers={"Cache-Control": "no-store"})


# --- mutations ----------------------------------------------------------------------------
#
# These change which French document a clinician is sent to, so they are gated on a shared
# secret when one is configured. The gate is opt-in rather than mandatory because /admin has no
# auth of its own yet: making it mandatory would lock the page's own controls out by default.
# Set ADMIN_SECRET and the write paths close.


def _auth_required() -> bool:
    return bool((os.getenv("ADMIN_SECRET") or "").strip())


def _require_admin(secret: Optional[str]) -> None:
    expected = (os.getenv("ADMIN_SECRET") or "").strip()
    if not expected:
        return
    if (secret or "").strip() != expected:
        raise HTTPException(status_code=401, detail="Invalid or missing admin secret.")


class PairRequest(BaseModel):
    enUrl: str
    frUrl: str
    frTitle: str = ""
    note: str = ""


def _store_error(exc: Exception) -> HTTPException:
    return HTTPException(status_code=502, detail=str(exc))


@app.post("/api/resource-links/pairs")
def create_pair(
    payload: PairRequest, x_admin_secret: Optional[str] = Header(default=None)
) -> Dict[str, Any]:
    _require_admin(x_admin_secret)
    from scripts.content_pipeline.overrides import OverrideStoreError, create_pair as store_pair

    try:
        override = store_pair(
            payload.enUrl,
            payload.frUrl,
            fr_title=payload.frTitle,
            note=payload.note,
        )
    except OverrideStoreError as exc:
        raise _store_error(exc) from exc
    return {"ok": True, "override": override.as_dict()}


class UnpairRequest(BaseModel):
    enUrl: str
    note: str = ""


@app.post("/api/resource-links/unpair")
def unpair(
    payload: UnpairRequest, x_admin_secret: Optional[str] = Header(default=None)
) -> Dict[str, Any]:
    """Remove whatever French link an English resource currently has, from any source.

    One endpoint for all three cases — manual row, committed baseline, live matcher — because
    from the reviewer's side they are one action. The store decides how to record it.
    """
    _require_admin(x_admin_secret)
    from scripts.content_pipeline.overrides import OverrideStoreError, create_unpair

    try:
        override = create_unpair(payload.enUrl, note=payload.note)
    except OverrideStoreError as exc:
        raise _store_error(exc) from exc
    return {"ok": True, "override": override.as_dict()}


@app.post("/api/resource-links/auto-pair")
def auto_pair(x_admin_secret: Optional[str] = Header(default=None)) -> Dict[str, Any]:
    """Run the matcher over everything still unpaired and record what it finds.

    The matcher already runs on every request, so this adds no matches that were not already
    being served — what it changes is that they become *rows*: visible in the table with a
    provenance, and removable. An implicit match recomputed per request is neither.
    """
    _require_admin(x_admin_secret)
    from scripts.content_pipeline.fetch import fetch_all, living_tools
    from scripts.content_pipeline.match import TIER_TOOL_NUMBER, match_resources
    from scripts.content_pipeline.overrides import OverrideStoreError, create_pair as store_pair
    from scripts.content_pipeline.urls import normalize_url

    pair_set, override_set = _effective_pair_set()
    if override_set.error:
        raise HTTPException(status_code=502, detail=override_set.error)

    fetched = fetch_all()
    result = match_resources(
        living_tools(fetched.english_tools), fetched.french_resources, pair_set
    )

    suppressed = override_set.suppressed()
    added: List[Dict[str, str]] = []
    skipped = 0
    try:
        for proposal in result.auto:
            # Same re-check as the publish path: only an exact tool-number match may be written
            # without someone having looked at it.
            if proposal.tier != TIER_TOOL_NUMBER:
                continue
            if normalize_url(proposal.en.url) in suppressed:
                skipped += 1
                continue
            store_pair(
                proposal.en.url,
                proposal.fr.url,
                fr_title=proposal.fr.title or "",
                note=proposal.evidence,
            )
            added.append({"enUrl": proposal.en.url, "frUrl": proposal.fr.url})
    except OverrideStoreError as exc:
        raise _store_error(exc) from exc

    return {
        "ok": True,
        "added": len(added),
        "skippedSuppressed": skipped,
        "pairs": added,
        "errors": fetched.errors,
    }


@app.delete("/api/resource-links/overrides/{override_id}")
def delete_override(
    override_id: str, x_admin_secret: Optional[str] = Header(default=None)
) -> Dict[str, Any]:
    _require_admin(x_admin_secret)
    from scripts.content_pipeline.overrides import OverrideStoreError, delete as store_delete

    try:
        removed = store_delete(override_id)
    except OverrideStoreError as exc:
        raise _store_error(exc) from exc
    if not removed:
        raise HTTPException(status_code=404, detail="No such override.")
    return {"ok": True, "deleted": 1}


@app.delete("/api/resource-links/overrides")
def clear_overrides(x_admin_secret: Optional[str] = Header(default=None)) -> Dict[str, Any]:
    """Drop every manual pairing, returning the app to the committed baseline.

    Safe by construction: the baseline is a committed file this endpoint cannot touch, so the
    worst case is losing hand-made pairings, not losing the reviewed ones.
    """
    _require_admin(x_admin_secret)
    from scripts.content_pipeline.overrides import OverrideStoreError, clear_all

    try:
        deleted = clear_all()
    except OverrideStoreError as exc:
        raise _store_error(exc) from exc
    return {"ok": True, "deleted": deleted}
